### PR TITLE
Update React to version 18 and other deps

### PR DESCRIPTION
**Pull request by HarelM**
This PR aims at updating some packages.
I'll keep this in draft until I'll be more happy with the results.
Current setup seems to work, I'll let the CI run and see how bad this is.
Packages that needs to be updated/replaces:
- [x] ~autocompete - The only warning left in the console is related to the autocomplete, which probably needs to be updated since it's a package that wasn't updated in the last 6 years.~ #611
- [x] ~Codemirror is also something that will need an update, but it looks too complicated at this point in time, so let's see how this goes.~ #891
- [ ] react-color
- [x] ~react-aria-menubutton~ #846
- [ ] Others?

Most of the changes here are related to types, which is good.

### CODE REVIEW

**Comment by HarelM** [comment]
Firefox tests are failing due to the following issue:
https://github.com/cypress-io/cypress/issues/29172

**Comment by HarelM** [comment]
Mostly up-to-date.
There's still a need to update some stale packages, which might prove harder than anticipated due to the fact that there might be a need to use a component library, which is a big effort.
So, this is out of scope for this PR.

**Review by nyurik — APPROVED** [review]
lgtm!

**Comment by nyurik** [comment]
is there a reason Firefox fails?  should we keep that test?

**Comment by HarelM** [comment]
See my comment about Firefox.

**Comment by HarelM** [comment]
@birkskyum I need your input here in order to merge this as you commented out about a problem in one of the components...

**Comment by HarelM** [comment]
In #846 you wrote something related to React 18 and incompatibility...

**Comment by birkskyum** [comment]
I think it was just npm that gave deprecation or version mismatch errors.

**Comment by birkskyum** [comment]
I wasn't able to get anything going

**Comment by HarelM** [comment]
Ahh, I see, so this is related to `legacy-peer-deps` flag that I added in order to get around the react version mismatch.
I would like to remove it in the future if possible, but I'm not very optimistic as it requires a lot of effort in replacing these old libraries, and it's not that easy.
In any case, I'll merge this and see what feedback I get from users as the sanity tests that I did seems that things are working as expected and also the tests pass (on chrome) which is good news.

**Pull request merged**
