### PR TITLE
localIdeographFontFamily: false to load CJK fonts

### LINKED ISSUE #892: add toggle `localIdeographFontFamily` options of MapLibre GL JS for CJK fonts
https://maplibre.org/maplibre-gl-js/docs/examples/local-ideographs/

- In MapLibre GL JS, if you need to load CJK fonts, you have to set `localIdeographFontFamily`.
- It seems that current version of Maputnik doesn't provide any feature to toggle this option.
- IMHO, it is better to add anything to toggle this options. What do you think?

### PR DESCRIPTION
**Pull request by Kanahiro**
close #892 

this changes works well for CJK fonts.

Screenshot 2024-03-25 at 22 04 36

### CODE REVIEW

**Comment by HarelM** [comment]
What would this change do to latin characters? Will they still be using the glyphs?
Also worth opening a PR for maplibre-gl to fix the type of the variable.

**Comment by Kanahiro** [comment]
@HarelM Thank you for checking this PR.
This change seems not to make no change on latin characters for me.

**Comment by HarelM** [comment]
Let's use this PR to update maplibre-gl to avoid introducing "as any", it should be a few days at max.

**Comment by HarelM** [comment]
4.1.2 should be available now.
Let me know if it solves the as any part.

**Comment by Kanahiro** [comment]
@HarelM Thank you for supporting! I've fixed.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Should be published in a few minutes, let me know if you encounter any issue with this.

**Pull request merged**
