### PR TITLE
Remove Storybook, cleanups

### PR DESCRIPTION
**Pull request by HarelM**
1. Changed references to point to this new repo
2. Fixed docker image publishing to point to ghcr.io.
3. Remove survey link - the survey is closed and there's no point in keeping it.
4. Remove storybook - Basically a storybook is the ability to look at components and see how they look and interact with them.
It's a powerful tool for developing component library with "live" documentation.
But it's an overkill for this project and I would like to reduce maintenance costs.
Currently all the "stories" are in javascript and not in typescript and it feels like a waste of time to try and maintain it, along with updating the storybook library itself and everything around it.

### CODE REVIEW

**Comment by nyurik** [comment]
@HarelM could you clarify what is the storybook and why we don't need it?

**Comment by HarelM** [comment]
It's mentioned in the channel.
Basically a storybook is the ability to look at components and see how they look and interact with them.
It's a powerful tool for developing component library with "live" documentation.
But it's an overkill for this project and I would like to reduce maintenance costs.
Currently all the "stories" are in javascript and not in typescript and it feels like a waste for me to try and maintain it, along with updating the storybook library itself and everything around it.

**Comment by nyurik** [comment]
Thx for explanation.  We should not rely on Slack channels to document our changes to the code, so lets make sure each change has clear explanation in the top comment of why it is being done - most people will have no idea there was a channel discussion when looking in the history of the project

**Comment by HarelM** [comment]
Can I merge this?

**Comment by nyurik** [comment]
Please update the first comment with the in-depth explanation of this change, and why it is not needed. This way that comment will go into the code's history, and can be easily viewed by anyone using git blame / viewing git log messages

**Comment by HarelM** [comment]
Updated the initial post.
Please squash and merge if this is good enough.

**Review by nyurik — APPROVED** [review]
thanks! feel free to merge

**Pull request merged**
