### PR TITLE
Use printf for generating version.go

### PR DESCRIPTION
**Pull request by starsep**
Flag -e is to "enable interpretation of backslash escapes"
Which might be a default, depends on a shell.

`sh -c 'echo "a\nb"'` on my OS prints
> a\nb

(no newline)

## Launch Checklist

 - [x] Briefly describe the changes in this PR.

### CODE REVIEW

**Comment by starsep** [comment]
Indeed.
> Error: error reading package: /home/runner/work/maputnik/maputnik/desktop/version.go:1:1: expected 'package', found '-'

I suspect also `-e` part was echoed. I will check later what exactly OS/shell is used in CI

**Comment by kevinschaul** [comment]
@starsep Possibly helpful: https://unix.stackexchange.com/questions/700675/why-is-echo-e-behaving-weird-in-a-makefile

**Comment by nyurik** [comment]
heh, that's why i prefer [just](https://github.com/casey/just), optionally with per-platform targets

**Comment by HarelM** [comment]
@nyurik did you review this PR? can it be merged?

**Review by nyurik — APPROVED** [review]

**Pull request merged**
