### PR TITLE
add README-ZH.md

### PR DESCRIPTION
**Pull request by jadelike-wine**
add chinese readme file

### CODE REVIEW

**Comment by HarelM** [comment]
While i think this is a great addition my main concern is about maintainence. I won't be able to update the Chinese readme and I'm concerned it might drift off.

**Comment by jadelike-wine** [comment]
> While i think this is a great addition my main concern is about maintainence. I won't be able to update the Chinese readme and I'm concerned it might drift off.

Thank you for your feedback.    I understand your concern about maintenance.    I would like to assure you that I am committed to regularly maintaining the Chinese documentation.

My company plans to use this GitHub project in the near future and is committed to maintaining and further developing the project.   As part of our adoption process, we are committed to maintaining documentation in Chinese to ensure that it remains accurate and up-to-date.

We have a team of developers and technical writers who are proficient in both English and Chinese.    We will be regularly reviewing and updating the Chinese documentation to reflect any changes to the project.

We believe that providing high-quality documentation in multiple languages is essential for a successful open source project.

We appreciate your understanding and support.

**Comment by nyurik** [comment]
Thx, I would love to have translated documentation, but I think the documentation is different from the Readme. Perhaps we should setup a mdbook in multiple languages?

**Comment by sharkAndshark** [comment]
Like the mdbook idea

**Comment by nyurik** [comment]
Comprehensive Rust used .po files ([info](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md)) -  seems interesting (they actually mentioned it in the link you gave [here](https://github.com/rust-lang/mdBook/issues/5#issuecomment-1496364248)), but this is a JS project, so if mkdocs works well - lets do that. @jadelike-wine would you be interested in starting that translation effort / setting up a doc site / help with translation there? Thx!

**Comment by sharkAndshark** [comment]
I'd love to help review the translation.  I think my Chinese is not bad lolll

**Comment by jadelike-wine** [comment]
> Comprehensive Rust used .po files ([info](https://github.com/google/comprehensive-rust/blob/main/TRANSLATIONS.md)) - seems interesting (they actually mentioned it in the link you gave [here](https://github.com/rust-lang/mdBook/issues/5#issuecomment-1496364248)), but this is a JS project, so if mkdocs works well - lets do that. @jadelike-wine would you be interested in starting that translation effort / setting up a doc site / help with translation there? Thx!

Ok, let me try to create a Mkdocs。we can do like this picture(https://squidfunk.github.io/mkdocs-material/assets/screenshots/language-selection.png)

**Pull request closed without merging**
